apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  namespace: demo-danweb
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-demo-danweb"
spec:
  tls:
  - hosts:
    - "demo-agendanweb.api-danweb-softwares.click"
    secretName: "demo-agendanweb-tls"
  - hosts:
    - "demo-agenda.app-danweb-softwares.click"
    secretName: "demo-agendanweb-front-tls"
  rules:
  - host: demo-agendanweb.api-danweb-softwares.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demo-agenda-back-svc
            port: 
              number: 80
  - host: demo-agenda.app-danweb-softwares.click
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: demo-agenda-front-svc
            port: 
              number: 80